[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3001"

[nixpacks]
node_version = "18.x" 