[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile && yarn build"

[deploy]
startCommand = "node src/server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "always"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "3001"
FRONTEND_URL = "https://ennygo-v2-production.up.railway.app"

[nixpacks]
node_version = "18.x" 