[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 3001

# Build arguments for Docker
[build.args]
VITE_SUPABASE_URL = { fromVariable = "VITE_SUPABASE_URL" }
VITE_SUPABASE_ANON_KEY = { fromVariable = "VITE_SUPABASE_ANON_KEY" }

# Environment variables for runtime
[deploy.env]
VITE_SUPABASE_URL = { fromVariable = "VITE_SUPABASE_URL" }
VITE_SUPABASE_ANON_KEY = { fromVariable = "VITE_SUPABASE_ANON_KEY" }

[nixpacks]
node_version = "18.x" 