[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildArgs = ["SUPABASE_URL", "SUPABASE_ANON_KEY"]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 3001

[nixpacks]
node_version = "18.x" 