[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && ROLLUP_SKIP_LOAD_NATIVE_PLUGIN=true npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
healthcheckInterval = 30

[nixpacks]
install_cmd = "npm install --include=dev" 