[build]
# Build commands
commands = [
  "yarn install --frozen-lockfile",
  "yarn build"
]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"

[nixpacks]
node_version = "18.x" 