[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile && yarn build"

[deploy]
startCommand = "node src/server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "always"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"

[nixpacks]
node_version = "18.x" 